apiVersion: v1
kind: Pod
metadata:
  name: pod2
  labels:
    app: pod2
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sh", "-c", "echo $SECRETVAR"]
    env:
    - name: SECRETVAR  # The name should not include a $ symbol
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: username