apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    app: pod1
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sh", "-c", "echo $CONFIGVAR"]
    env:
    - name: CONFIGVAR  # The name should not include a $ symbol
      valueFrom:
        configMapKeyRef:
          name: myconfigmap
          key: username
